import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";
import MySessionProvider from "./_providers/MySessionProvider";
import Ncontext from "./_contexts/Ncontext";
import DisplayProdectApi from "./shop/DisplayProdectApi";
import CallGetLoggedUserWishlistApi from "@/CallAPIs/CallGetLoggedUserWishlistApi";
import { emptyAddToCartResponse, emptyWishlistResponse } from "@/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [userCart, userWishlist] = await Promise.all([
    DisplayProdectApi().catch(() => emptyAddToCartResponse),
    CallGetLoggedUserWishlistApi().catch(() => emptyWishlistResponse),
  ]);
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">

        <MySessionProvider>
          <Ncontext userCart={userCart} userWishlist={userWishlist}>


        <Toaster />
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1 pt-28 sm:pt-24">{children}</main>
          <Footer />
        </div>
          </Ncontext>
        </MySessionProvider>
      </body>
    </html>
  );
}
